/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.dialog;

import database.Konfigurasi;
import gui.Sign;
import java.awt.FontFormatException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author haris
 */
public class GuestAlert extends javax.swing.JDialog {

    /**
     * Creates new form GuestAlert
     */
    public GuestAlert(java.awt.Frame parent) {
        this.parent = parent;
        
        try {
            this.konfigurasi = new Konfigurasi();
        } catch (IOException | FontFormatException ex) {
            Logger.getLogger(GuestAlert.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelSI = new javax.swing.JPanel();
        panelSIHeader = new javax.swing.JPanel();
        labelSIHeader = new javax.swing.JLabel();
        panelSIBody = new javax.swing.JPanel();
        panelSIDeskripsi = new javax.swing.JTextArea();
        panelSIFooter = new javax.swing.JPanel();
        buttonSISekarang = new javax.swing.JButton();
        buttonSIKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("YukBeliYuk - Guest Alert");
        setModal(true);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 450));

        panelSI.setBackground(new java.awt.Color(254, 250, 224));
        panelSI.setMaximumSize(new java.awt.Dimension(600, 450));
        panelSI.setMinimumSize(new java.awt.Dimension(600, 450));
        panelSI.setPreferredSize(new java.awt.Dimension(600, 450));
        panelSI.setLayout(new javax.swing.BoxLayout(panelSI, javax.swing.BoxLayout.PAGE_AXIS));

        panelSIHeader.setBackground(new java.awt.Color(254, 250, 224));
        panelSIHeader.setMaximumSize(new java.awt.Dimension(600, 60));
        panelSIHeader.setLayout(new java.awt.GridBagLayout());

        labelSIHeader.setFont(konfigurasi.getPhilosopher(36));
        labelSIHeader.setText("Sign in Dulu Yuk");
        labelSIHeader.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        labelSIHeader.setMaximumSize(new java.awt.Dimension(540, 60));
        labelSIHeader.setMinimumSize(new java.awt.Dimension(540, 60));
        labelSIHeader.setPreferredSize(new java.awt.Dimension(540, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 30);
        panelSIHeader.add(labelSIHeader, gridBagConstraints);

        panelSI.add(panelSIHeader);

        panelSIBody.setBackground(new java.awt.Color(254, 250, 224));
        panelSIBody.setLayout(new java.awt.GridBagLayout());

        panelSIDeskripsi.setEditable(false);
        panelSIDeskripsi.setBackground(new java.awt.Color(254, 250, 224));
        panelSIDeskripsi.setColumns(20);
        panelSIDeskripsi.setFont(konfigurasi.getRoboto(14));
        panelSIDeskripsi.setText("\nUntuk mengakses semua fitur dari aplikasi, Anda harus Sign in terlebih dahulu.\n\nDengan melakukan Sign in Anda dapat:\n- Membeli buku sebanyak-banyaknya.\n- Membuat review terhadap buku yang anda beli.\n\nKami akan menjaga data anda sebaik-baiknya, hanya saja jangan gunakan password \nyang biasa anda gunakan.");
        panelSIDeskripsi.setWrapStyleWord(true);
        panelSIDeskripsi.setBorder(null);
        panelSIDeskripsi.setMaximumSize(new java.awt.Dimension(550, 275));
        panelSIDeskripsi.setMinimumSize(new java.awt.Dimension(550, 275));
        panelSIDeskripsi.setPreferredSize(new java.awt.Dimension(550, 275));
        panelSIBody.add(panelSIDeskripsi, new java.awt.GridBagConstraints());

        panelSI.add(panelSIBody);

        panelSIFooter.setBackground(new java.awt.Color(250, 237, 205));
        panelSIFooter.setMaximumSize(new java.awt.Dimension(600, 75));
        panelSIFooter.setMinimumSize(new java.awt.Dimension(600, 75));

        buttonSISekarang.setBackground(new java.awt.Color(212, 163, 115));
        buttonSISekarang.setFont(konfigurasi.getRobotoBold(14));
        buttonSISekarang.setText("Sign in Sekarang");
        buttonSISekarang.setMaximumSize(new java.awt.Dimension(175, 50));
        buttonSISekarang.setMinimumSize(new java.awt.Dimension(175, 50));
        buttonSISekarang.setPreferredSize(new java.awt.Dimension(175, 50));
        buttonSISekarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSISekarangActionPerformed(evt);
            }
        });

        buttonSIKembali.setBackground(new java.awt.Color(212, 163, 115));
        buttonSIKembali.setFont(konfigurasi.getRobotoBold(14));
        buttonSIKembali.setText("Kembali");
        buttonSIKembali.setMaximumSize(new java.awt.Dimension(175, 50));
        buttonSIKembali.setMinimumSize(new java.awt.Dimension(175, 50));
        buttonSIKembali.setPreferredSize(new java.awt.Dimension(175, 50));
        buttonSIKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSIKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSIFooterLayout = new javax.swing.GroupLayout(panelSIFooter);
        panelSIFooter.setLayout(panelSIFooterLayout);
        panelSIFooterLayout.setHorizontalGroup(
            panelSIFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSIFooterLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(buttonSIKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSISekarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(199, 199, 199))
        );
        panelSIFooterLayout.setVerticalGroup(
            panelSIFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSIFooterLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelSIFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSISekarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSIKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );

        panelSI.add(panelSIFooter);

        getContentPane().add(panelSI, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSISekarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSISekarangActionPerformed
        // TODO add your handling code here:
        Sign SI = new Sign();
        SI.setLocation(parent.getLocation());
        SI.setSize(parent.getSize());
        SI.setVisible(true);

        parent.dispose();
        dispose();
    }//GEN-LAST:event_buttonSISekarangActionPerformed

    private void buttonSIKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSIKembaliActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonSIKembaliActionPerformed

    private java.awt.Frame parent;
    private Konfigurasi konfigurasi;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSIKembali;
    private javax.swing.JButton buttonSISekarang;
    private javax.swing.JLabel labelSIHeader;
    private javax.swing.JPanel panelSI;
    private javax.swing.JPanel panelSIBody;
    private javax.swing.JTextArea panelSIDeskripsi;
    private javax.swing.JPanel panelSIFooter;
    private javax.swing.JPanel panelSIHeader;
    // End of variables declaration//GEN-END:variables
}
