/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author haris
 */
public class Konfirmasi extends javax.swing.JFrame {

    /**
     * Creates new form Konfirmasi
     */
    public Konfirmasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        fillerPreHeader = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        labelTitle = new javax.swing.JLabel();
        fillerMidHeader = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        labelEmail = new javax.swing.JLabel();
        fillerMid2Header = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        labelUserProfile = new javax.swing.JLabel();
        fillerPosHeader = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        panelBody = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        panelFooter = new javax.swing.JPanel();
        fillerPreHeader1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        labelTitle1 = new javax.swing.JLabel();
        fillerMidHeader1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jButton2 = new javax.swing.JButton();
        fillerMid2Header1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jButton1 = new javax.swing.JButton();
        fillerPosHeader1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        panelHeader.setBackground(new java.awt.Color(204, 213, 174));
        panelHeader.setMaximumSize(new java.awt.Dimension(32767, 60));
        panelHeader.setMinimumSize(new java.awt.Dimension(800, 60));
        panelHeader.setPreferredSize(new java.awt.Dimension(800, 60));
        panelHeader.setLayout(new javax.swing.BoxLayout(panelHeader, javax.swing.BoxLayout.LINE_AXIS));
        panelHeader.add(fillerPreHeader);

        labelTitle.setFont(new java.awt.Font("Philosopher", 0, 36)); // NOI18N
        labelTitle.setText("YukBayarYuk");
        panelHeader.add(labelTitle);
        panelHeader.add(fillerMidHeader);

        labelEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(255, 255, 255));
        labelEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelEmail.setText("user@gmail.com");
        panelHeader.add(labelEmail);
        panelHeader.add(fillerMid2Header);

        labelUserProfile.setFont(new java.awt.Font("Font Awesome 5 Free Solid", 0, 36)); // NOI18N
        labelUserProfile.setForeground(new java.awt.Color(255, 255, 255));
        labelUserProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUserProfile.setText("");
        labelUserProfile.setMaximumSize(new java.awt.Dimension(30, 30));
        labelUserProfile.setMinimumSize(new java.awt.Dimension(30, 30));
        labelUserProfile.setPreferredSize(new java.awt.Dimension(30, 30));
        panelHeader.add(labelUserProfile);
        panelHeader.add(fillerPosHeader);

        getContentPane().add(panelHeader);

        panelBody.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(254, 250, 224));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        panelBody.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelBody);

        panelFooter.setBackground(new java.awt.Color(250, 237, 205));
        panelFooter.setMaximumSize(new java.awt.Dimension(32767, 60));
        panelFooter.setMinimumSize(new java.awt.Dimension(800, 60));
        panelFooter.setPreferredSize(new java.awt.Dimension(800, 60));
        panelFooter.setLayout(new javax.swing.BoxLayout(panelFooter, javax.swing.BoxLayout.LINE_AXIS));
        panelFooter.add(fillerPreHeader1);

        labelTitle1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        labelTitle1.setText("Total: ");
        panelFooter.add(labelTitle1);
        panelFooter.add(fillerMidHeader1);

        jButton2.setBackground(new java.awt.Color(212, 163, 115));
        jButton2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton2.setText("Kembali");
        jButton2.setMaximumSize(new java.awt.Dimension(105, 35));
        jButton2.setMinimumSize(new java.awt.Dimension(105, 35));
        jButton2.setPreferredSize(new java.awt.Dimension(105, 35));
        panelFooter.add(jButton2);
        panelFooter.add(fillerMid2Header1);

        jButton1.setBackground(new java.awt.Color(212, 163, 115));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton1.setText("Konfirmasi");
        jButton1.setMaximumSize(new java.awt.Dimension(105, 35));
        jButton1.setMinimumSize(new java.awt.Dimension(105, 35));
        jButton1.setPreferredSize(new java.awt.Dimension(105, 35));
        panelFooter.add(jButton1);
        panelFooter.add(fillerPosHeader1);

        getContentPane().add(panelFooter);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler fillerMid2Header;
    private javax.swing.Box.Filler fillerMid2Header1;
    private javax.swing.Box.Filler fillerMidHeader;
    private javax.swing.Box.Filler fillerMidHeader1;
    private javax.swing.Box.Filler fillerPosHeader;
    private javax.swing.Box.Filler fillerPosHeader1;
    private javax.swing.Box.Filler fillerPreHeader;
    private javax.swing.Box.Filler fillerPreHeader1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTitle1;
    private javax.swing.JLabel labelUserProfile;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelHeader;
    // End of variables declaration//GEN-END:variables
}
