/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import classes.Pembeli;
import gui.dialog.InfoPengguna;

/**
 *
 * @author haris
 */
public class Konfirmasi extends javax.swing.JFrame {

    /**
     * Creates new form Konfirmasi
     * 
     * @param pembeli
     */
    public Konfirmasi(Pembeli pembeli) {
        this.pembeli = pembeli;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        fillerPreHeader = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        labelTitle = new javax.swing.JLabel();
        fillerMidHeader = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        labelEmail = new javax.swing.JLabel();
        fillerMid2Header = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        labelUserProfile = new javax.swing.JLabel();
        fillerPosHeader = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        panelBody = new javax.swing.JPanel();
        scrollBackground = new javax.swing.JScrollPane();
        panelBackground = new javax.swing.JPanel();
        panelFooter = new javax.swing.JPanel();
        fillerPreFooter = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        labelTotal = new javax.swing.JLabel();
        labelBiaya = new javax.swing.JLabel();
        fillerMidFooter1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        buttonKembali = new javax.swing.JButton();
        fillerMidFooter2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        buttonKonfirmasi = new javax.swing.JButton();
        fillerPosFooter = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        panelHeader.setBackground(new java.awt.Color(204, 213, 174));
        panelHeader.setMaximumSize(new java.awt.Dimension(32767, 60));
        panelHeader.setMinimumSize(new java.awt.Dimension(800, 60));
        panelHeader.setPreferredSize(new java.awt.Dimension(800, 60));
        panelHeader.setLayout(new javax.swing.BoxLayout(panelHeader, javax.swing.BoxLayout.LINE_AXIS));
        panelHeader.add(fillerPreHeader);

        labelTitle.setFont(new java.awt.Font("Philosopher", 0, 36)); // NOI18N
        labelTitle.setText("YukBayarYuk");
        panelHeader.add(labelTitle);
        panelHeader.add(fillerMidHeader);

        labelEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(255, 255, 255));
        labelEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelEmail.setText("user@gmail.com");
        panelHeader.add(labelEmail);
        panelHeader.add(fillerMid2Header);

        labelUserProfile.setFont(new java.awt.Font("Font Awesome 5 Free Solid", 0, 36)); // NOI18N
        labelUserProfile.setForeground(new java.awt.Color(255, 255, 255));
        labelUserProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUserProfile.setText("");
        labelUserProfile.setMaximumSize(new java.awt.Dimension(30, 30));
        labelUserProfile.setMinimumSize(new java.awt.Dimension(30, 30));
        labelUserProfile.setPreferredSize(new java.awt.Dimension(30, 30));
        labelUserProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelUserProfileMouseClicked(evt);
            }
        });
        panelHeader.add(labelUserProfile);
        panelHeader.add(fillerPosHeader);

        getContentPane().add(panelHeader);

        panelBody.setLayout(new java.awt.BorderLayout());

        scrollBackground.setBorder(null);
        scrollBackground.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollBackground.setToolTipText("");

        panelBackground.setBackground(new java.awt.Color(254, 250, 224));

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        scrollBackground.setViewportView(panelBackground);

        panelBody.add(scrollBackground, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelBody);

        panelFooter.setBackground(new java.awt.Color(250, 237, 205));
        panelFooter.setMaximumSize(new java.awt.Dimension(32767, 60));
        panelFooter.setMinimumSize(new java.awt.Dimension(800, 60));
        panelFooter.setPreferredSize(new java.awt.Dimension(800, 60));
        panelFooter.setLayout(new javax.swing.BoxLayout(panelFooter, javax.swing.BoxLayout.LINE_AXIS));
        panelFooter.add(fillerPreFooter);

        labelTotal.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        labelTotal.setText("Total: ");
        panelFooter.add(labelTotal);

        labelBiaya.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        panelFooter.add(labelBiaya);
        panelFooter.add(fillerMidFooter1);

        buttonKembali.setBackground(new java.awt.Color(212, 163, 115));
        buttonKembali.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        buttonKembali.setText("Kembali");
        buttonKembali.setMaximumSize(new java.awt.Dimension(105, 35));
        buttonKembali.setMinimumSize(new java.awt.Dimension(105, 35));
        buttonKembali.setPreferredSize(new java.awt.Dimension(105, 35));
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });
        panelFooter.add(buttonKembali);
        panelFooter.add(fillerMidFooter2);

        buttonKonfirmasi.setBackground(new java.awt.Color(212, 163, 115));
        buttonKonfirmasi.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        buttonKonfirmasi.setText("Konfirmasi");
        buttonKonfirmasi.setMaximumSize(new java.awt.Dimension(105, 35));
        buttonKonfirmasi.setMinimumSize(new java.awt.Dimension(105, 35));
        buttonKonfirmasi.setPreferredSize(new java.awt.Dimension(105, 35));
        panelFooter.add(buttonKonfirmasi);
        panelFooter.add(fillerPosFooter);

        getContentPane().add(panelFooter);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        // TODO add your handling code here:
        PilihanBuku PB = new PilihanBuku(pembeli);
        PB.setLocation(getLocation());
        PB.setSize(getSize());
        PB.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_buttonKembaliActionPerformed

    private void labelUserProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUserProfileMouseClicked
        // TODO add your handling code here:
        InfoPengguna IP = new InfoPengguna(this, pembeli);
        IP.setLocationRelativeTo(null);
        IP.setVisible(true);
    }//GEN-LAST:event_labelUserProfileMouseClicked

    private Pembeli pembeli;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKembali;
    private javax.swing.JButton buttonKonfirmasi;
    private javax.swing.Box.Filler fillerMid2Header;
    private javax.swing.Box.Filler fillerMidFooter1;
    private javax.swing.Box.Filler fillerMidFooter2;
    private javax.swing.Box.Filler fillerMidHeader;
    private javax.swing.Box.Filler fillerPosFooter;
    private javax.swing.Box.Filler fillerPosHeader;
    private javax.swing.Box.Filler fillerPreFooter;
    private javax.swing.Box.Filler fillerPreHeader;
    private javax.swing.JLabel labelBiaya;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelUserProfile;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JScrollPane scrollBackground;
    // End of variables declaration//GEN-END:variables
}
