package gui;

public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelBackground = new javax.swing.JPanel();
        panelSign = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JPasswordField();
        buttonSignIn = new javax.swing.JButton();
        buttonSignIn1 = new javax.swing.JButton();
        buttonSignIn2 = new javax.swing.JButton();
        panelSupport = new javax.swing.JPanel();
        labelApplicationName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YukBacaYuk - Sign In");
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(800, 600));

        panelBackground.setBackground(new java.awt.Color(204, 213, 174));
        panelBackground.setToolTipText(null);
        panelBackground.setLayout(new java.awt.GridBagLayout());

        panelSign.setBackground(new java.awt.Color(233, 237, 201));
        panelSign.setMaximumSize(new java.awt.Dimension(400, 300));
        panelSign.setMinimumSize(new java.awt.Dimension(400, 300));
        panelSign.setPreferredSize(new java.awt.Dimension(400, 300));
        java.awt.GridBagLayout panelSignLayout = new java.awt.GridBagLayout();
        panelSignLayout.columnWidths = new int[] {0, 0, 0};
        panelSignLayout.rowHeights = new int[] {0, 20, 0, 20, 0};
        panelSign.setLayout(panelSignLayout);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setText("Email:");
        jLabel1.setMaximumSize(new java.awt.Dimension(40, 15));
        jLabel1.setMinimumSize(new java.awt.Dimension(40, 15));
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelSign.add(jLabel1, gridBagConstraints);

        fieldEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fieldEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldEmail.setPreferredSize(new java.awt.Dimension(300, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        panelSign.add(fieldEmail, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setText("Password:");
        jLabel2.setMaximumSize(new java.awt.Dimension(66, 15));
        jLabel2.setMinimumSize(new java.awt.Dimension(66, 15));
        jLabel2.setPreferredSize(new java.awt.Dimension(66, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelSign.add(jLabel2, gridBagConstraints);

        fieldPassword.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fieldPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldPassword.setPreferredSize(new java.awt.Dimension(300, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        panelSign.add(fieldPassword, gridBagConstraints);

        buttonSignIn.setBackground(new java.awt.Color(204, 213, 174));
        buttonSignIn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        buttonSignIn.setText("Sign In");
        buttonSignIn.setMaximumSize(new java.awt.Dimension(150, 50));
        buttonSignIn.setMinimumSize(new java.awt.Dimension(150, 50));
        buttonSignIn.setPreferredSize(new java.awt.Dimension(150, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        panelSign.add(buttonSignIn, gridBagConstraints);

        buttonSignIn1.setBackground(new java.awt.Color(204, 213, 174));
        buttonSignIn1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        buttonSignIn1.setText("Create Account");
        buttonSignIn1.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        panelSign.add(buttonSignIn1, gridBagConstraints);

        buttonSignIn2.setBackground(new java.awt.Color(204, 213, 174));
        buttonSignIn2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        buttonSignIn2.setText("Sign As Guest");
        buttonSignIn2.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        panelSign.add(buttonSignIn2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        panelBackground.add(panelSign, gridBagConstraints);

        panelSupport.setBackground(new java.awt.Color(204, 213, 174));
        panelSupport.setPreferredSize(new java.awt.Dimension(600, 450));
        panelSupport.setLayout(new java.awt.BorderLayout());

        labelApplicationName.setFont(new java.awt.Font("Philosopher", 0, 48)); // NOI18N
        labelApplicationName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelApplicationName.setText("YukBacaYuk");
        labelApplicationName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelSupport.add(labelApplicationName, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panelBackground.add(panelSupport, gridBagConstraints);

        getContentPane().add(panelBackground, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSignIn;
    private javax.swing.JButton buttonSignIn1;
    private javax.swing.JButton buttonSignIn2;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelApplicationName;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelSign;
    private javax.swing.JPanel panelSupport;
    // End of variables declaration//GEN-END:variables
}
