package gui;

public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelBackground = new javax.swing.JPanel();
        panelSign = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        fieldConfirmPassword = new javax.swing.JPasswordField();
        buttonSignUp = new javax.swing.JButton();
        panelSupport = new javax.swing.JPanel();
        labelApplicationName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YukBacaYuk - Sign In");
        setMinimumSize(new java.awt.Dimension(600, 500));

        panelBackground.setBackground(new java.awt.Color(204, 213, 174));
        panelBackground.setToolTipText(null);
        panelBackground.setMinimumSize(new java.awt.Dimension(800, 600));
        panelBackground.setPreferredSize(new java.awt.Dimension(800, 600));
        panelBackground.setLayout(new java.awt.GridBagLayout());

        panelSign.setBackground(new java.awt.Color(233, 237, 201));
        panelSign.setPreferredSize(new java.awt.Dimension(400, 350));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0};
        jPanel2Layout.rowHeights = new int[] {0, 15, 0, 15, 0, 15, 0};
        panelSign.setLayout(jPanel2Layout);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setText("Email:");
        jLabel1.setMaximumSize(new java.awt.Dimension(40, 15));
        jLabel1.setMinimumSize(new java.awt.Dimension(40, 15));
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelSign.add(jLabel1, gridBagConstraints);

        fieldEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fieldEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldEmail.setPreferredSize(new java.awt.Dimension(300, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        panelSign.add(fieldEmail, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setText("Password:");
        jLabel2.setMaximumSize(new java.awt.Dimension(40, 15));
        jLabel2.setMinimumSize(new java.awt.Dimension(40, 15));
        jLabel2.setPreferredSize(new java.awt.Dimension(40, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelSign.add(jLabel2, gridBagConstraints);

        fieldPassword.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fieldPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldPassword.setPreferredSize(new java.awt.Dimension(300, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        panelSign.add(fieldPassword, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setText("Confirm Password:");
        jLabel3.setMaximumSize(new java.awt.Dimension(40, 15));
        jLabel3.setMinimumSize(new java.awt.Dimension(40, 15));
        jLabel3.setPreferredSize(new java.awt.Dimension(40, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelSign.add(jLabel3, gridBagConstraints);

        fieldConfirmPassword.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fieldConfirmPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldConfirmPassword.setPreferredSize(new java.awt.Dimension(300, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        panelSign.add(fieldConfirmPassword, gridBagConstraints);

        buttonSignUp.setBackground(new java.awt.Color(204, 213, 174));
        buttonSignUp.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        buttonSignUp.setText("Sign Up");
        buttonSignUp.setPreferredSize(new java.awt.Dimension(150, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        panelSign.add(buttonSignUp, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        panelBackground.add(panelSign, gridBagConstraints);

        panelSupport.setBackground(new java.awt.Color(204, 213, 174));
        panelSupport.setPreferredSize(new java.awt.Dimension(600, 450));
        panelSupport.setLayout(new java.awt.BorderLayout());

        labelApplicationName.setFont(new java.awt.Font("Philosopher", 0, 48)); // NOI18N
        labelApplicationName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelApplicationName.setText("YukDaftarYuk");
        labelApplicationName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelSupport.add(labelApplicationName, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panelBackground.add(panelSupport, gridBagConstraints);

        getContentPane().add(panelBackground, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSignUp;
    private javax.swing.JPasswordField fieldConfirmPassword;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelApplicationName;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelSign;
    private javax.swing.JPanel panelSupport;
    // End of variables declaration//GEN-END:variables
}
