package gui;

public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelBackground = new javax.swing.JPanel();
        panelSign = new javax.swing.JPanel();
        fieldEmail = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JPasswordField();
        buttonSignIn = new javax.swing.JButton();
        panelSupport = new javax.swing.JPanel();
        labelApplicationName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YukBacaYuk - Sign In");
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(800, 600));

        panelBackground.setBackground(new java.awt.Color(204, 213, 174));
        panelBackground.setToolTipText("");
        panelBackground.setLayout(new java.awt.GridBagLayout());

        panelSign.setBackground(new java.awt.Color(233, 237, 201));
        panelSign.setPreferredSize(new java.awt.Dimension(400, 300));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0};
        jPanel2Layout.rowHeights = new int[] {0, 20, 0, 20, 0};
        panelSign.setLayout(jPanel2Layout);

        fieldEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fieldEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldEmail.setPreferredSize(new java.awt.Dimension(300, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panelSign.add(fieldEmail, gridBagConstraints);

        fieldPassword.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fieldPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldPassword.setPreferredSize(new java.awt.Dimension(300, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        panelSign.add(fieldPassword, gridBagConstraints);

        buttonSignIn.setBackground(new java.awt.Color(204, 213, 174));
        buttonSignIn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        buttonSignIn.setText("Sign In");
        buttonSignIn.setPreferredSize(new java.awt.Dimension(150, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        panelSign.add(buttonSignIn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        panelBackground.add(panelSign, gridBagConstraints);

        panelSupport.setBackground(new java.awt.Color(204, 213, 174));
        panelSupport.setPreferredSize(new java.awt.Dimension(600, 450));
        panelSupport.setLayout(new java.awt.BorderLayout());

        labelApplicationName.setFont(new java.awt.Font("Philosopher", 0, 48)); // NOI18N
        labelApplicationName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelApplicationName.setText("YukBacaYuk");
        labelApplicationName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelSupport.add(labelApplicationName, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panelBackground.add(panelSupport, gridBagConstraints);

        getContentPane().add(panelBackground, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSignIn;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JLabel labelApplicationName;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelSign;
    private javax.swing.JPanel panelSupport;
    // End of variables declaration//GEN-END:variables
}
