package gui;

import classes.Pembeli;
import classes.Regist;
import database.Konfigurasi;
import gui.dialog.InfoPengguna;
import java.io.IOException;
import java.awt.CardLayout;
import java.awt.FontFormatException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Sign extends javax.swing.JFrame {

    public Sign() {
        try {
            this.konfigurasi = new Konfigurasi();
        } catch (IOException | FontFormatException ex) {
            Logger.getLogger(Sign.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initComponents();
        this.card = (CardLayout) getContentPane().getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelSIBackground = new javax.swing.JPanel();
        panelSI = new javax.swing.JPanel();
        labelSIEmail = new javax.swing.JLabel();
        fieldSIEmail = new javax.swing.JTextField();
        labelSIPassword = new javax.swing.JLabel();
        fieldSIPassword = new javax.swing.JPasswordField();
        buttonSignIn = new javax.swing.JButton();
        buttonCreateAccount = new javax.swing.JButton();
        buttonSignAsGuest = new javax.swing.JButton();
        panelSISupport = new javax.swing.JPanel();
        labelSITitle = new javax.swing.JLabel();
        panelSUBackground = new javax.swing.JPanel();
        panelSU = new javax.swing.JPanel();
        labelSUEmail = new javax.swing.JLabel();
        fieldSUEmail = new javax.swing.JTextField();
        labelSUPassword = new javax.swing.JLabel();
        fieldSUPassword = new javax.swing.JPasswordField();
        labelSUConPassword = new javax.swing.JLabel();
        fieldSUConPassword = new javax.swing.JPasswordField();
        buttonCancel = new javax.swing.JButton();
        buttonSignUp = new javax.swing.JButton();
        panelSUSupport = new javax.swing.JPanel();
        labelSUTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YukBacaYuk - Sign In");
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(822, 622));
        getContentPane().setLayout(new java.awt.CardLayout());

        panelSIBackground.setBackground(new java.awt.Color(204, 213, 174));
        panelSIBackground.setToolTipText(null);
        panelSIBackground.setLayout(new java.awt.GridBagLayout());

        panelSI.setBackground(new java.awt.Color(233, 237, 201));
        panelSI.setMaximumSize(new java.awt.Dimension(400, 300));
        panelSI.setMinimumSize(new java.awt.Dimension(400, 300));
        panelSI.setPreferredSize(new java.awt.Dimension(400, 300));
        java.awt.GridBagLayout panelSignLayout = new java.awt.GridBagLayout();
        panelSignLayout.columnWidths = new int[] {0, 0, 0};
        panelSignLayout.rowHeights = new int[] {0, 20, 0, 20, 0};
        panelSI.setLayout(panelSignLayout);

        labelSIEmail.setFont(konfigurasi.getRobotoBold(14));
        labelSIEmail.setText("Email:");
        labelSIEmail.setMaximumSize(new java.awt.Dimension(40, 15));
        labelSIEmail.setMinimumSize(new java.awt.Dimension(40, 15));
        labelSIEmail.setPreferredSize(new java.awt.Dimension(40, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelSI.add(labelSIEmail, gridBagConstraints);

        fieldSIEmail.setFont(konfigurasi.getRoboto(14));
        fieldSIEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldSIEmail.setPreferredSize(new java.awt.Dimension(300, 50));
        fieldSIEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldSIEmailFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        panelSI.add(fieldSIEmail, gridBagConstraints);

        labelSIPassword.setFont(konfigurasi.getRobotoBold(14));
        labelSIPassword.setText("Password:");
        labelSIPassword.setMaximumSize(new java.awt.Dimension(66, 15));
        labelSIPassword.setMinimumSize(new java.awt.Dimension(66, 15));
        labelSIPassword.setPreferredSize(new java.awt.Dimension(66, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelSI.add(labelSIPassword, gridBagConstraints);

        fieldSIPassword.setFont(konfigurasi.getRoboto(14));
        fieldSIPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldSIPassword.setPreferredSize(new java.awt.Dimension(300, 50));
        fieldSIPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldSIPasswordFocusGained(evt);
            }
        });
        fieldSIPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldSIPasswordKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        panelSI.add(fieldSIPassword, gridBagConstraints);

        buttonSignIn.setBackground(new java.awt.Color(204, 213, 174));
        buttonSignIn.setFont(konfigurasi.getRobotoBold(14));
        buttonSignIn.setText("Sign In");
        buttonSignIn.setMaximumSize(new java.awt.Dimension(150, 50));
        buttonSignIn.setMinimumSize(new java.awt.Dimension(150, 50));
        buttonSignIn.setPreferredSize(new java.awt.Dimension(150, 50));
        buttonSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignInActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        panelSI.add(buttonSignIn, gridBagConstraints);

        buttonCreateAccount.setBackground(new java.awt.Color(204, 213, 174));
        buttonCreateAccount.setFont(konfigurasi.getRobotoBold(14));
        buttonCreateAccount.setText("Create Account");
        buttonCreateAccount.setPreferredSize(new java.awt.Dimension(150, 25));
        buttonCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateAccountActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        panelSI.add(buttonCreateAccount, gridBagConstraints);

        buttonSignAsGuest.setBackground(new java.awt.Color(204, 213, 174));
        buttonSignAsGuest.setFont(konfigurasi.getRobotoBold(14));
        buttonSignAsGuest.setText("Sign As Guest");
        buttonSignAsGuest.setPreferredSize(new java.awt.Dimension(150, 25));
        buttonSignAsGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignAsGuestActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        panelSI.add(buttonSignAsGuest, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        panelSIBackground.add(panelSI, gridBagConstraints);

        panelSISupport.setBackground(new java.awt.Color(204, 213, 174));
        panelSISupport.setPreferredSize(new java.awt.Dimension(600, 450));
        panelSISupport.setLayout(new java.awt.BorderLayout());

        labelSITitle.setFont(konfigurasi.getPhilosopher(48));
        labelSITitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSITitle.setText("YukBacaYuk");
        labelSITitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelSISupport.add(labelSITitle, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panelSIBackground.add(panelSISupport, gridBagConstraints);

        getContentPane().add(panelSIBackground, "SignIn");

        panelSUBackground.setBackground(new java.awt.Color(204, 213, 174));
        panelSUBackground.setToolTipText(null);
        panelSUBackground.setMinimumSize(new java.awt.Dimension(800, 600));
        panelSUBackground.setPreferredSize(new java.awt.Dimension(800, 600));
        panelSUBackground.setLayout(new java.awt.GridBagLayout());

        panelSU.setBackground(new java.awt.Color(233, 237, 201));
        panelSU.setPreferredSize(new java.awt.Dimension(400, 350));
        java.awt.GridBagLayout panelSULayout = new java.awt.GridBagLayout();
        panelSULayout.columnWidths = new int[] {0, 0, 0, 0};
        panelSULayout.rowHeights = new int[] {0, 20, 0, 20, 0, 20, 0};
        panelSU.setLayout(panelSULayout);

        labelSUEmail.setFont(konfigurasi.getRobotoBold(14));
        labelSUEmail.setText("Email:");
        labelSUEmail.setMaximumSize(new java.awt.Dimension(40, 15));
        labelSUEmail.setMinimumSize(new java.awt.Dimension(40, 15));
        labelSUEmail.setPreferredSize(new java.awt.Dimension(40, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelSU.add(labelSUEmail, gridBagConstraints);

        fieldSUEmail.setFont(konfigurasi.getRoboto(14));
        fieldSUEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldSUEmail.setPreferredSize(new java.awt.Dimension(300, 50));
        fieldSUEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldSUEmailFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        panelSU.add(fieldSUEmail, gridBagConstraints);

        labelSUPassword.setFont(konfigurasi.getRobotoBold(14));
        labelSUPassword.setText("Password:");
        labelSUPassword.setMaximumSize(new java.awt.Dimension(40, 15));
        labelSUPassword.setMinimumSize(new java.awt.Dimension(40, 15));
        labelSUPassword.setPreferredSize(new java.awt.Dimension(40, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelSU.add(labelSUPassword, gridBagConstraints);

        fieldSUPassword.setFont(konfigurasi.getRoboto(14));
        fieldSUPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldSUPassword.setPreferredSize(new java.awt.Dimension(300, 50));
        fieldSUPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldSUPasswordFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        panelSU.add(fieldSUPassword, gridBagConstraints);

        labelSUConPassword.setFont(konfigurasi.getRobotoBold(14));
        labelSUConPassword.setText("Confirm Password:");
        labelSUConPassword.setMaximumSize(new java.awt.Dimension(40, 15));
        labelSUConPassword.setMinimumSize(new java.awt.Dimension(40, 15));
        labelSUConPassword.setPreferredSize(new java.awt.Dimension(40, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelSU.add(labelSUConPassword, gridBagConstraints);

        fieldSUConPassword.setFont(konfigurasi.getRoboto(14));
        fieldSUConPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldSUConPassword.setPreferredSize(new java.awt.Dimension(300, 50));
        fieldSUConPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldSUConPasswordKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        panelSU.add(fieldSUConPassword, gridBagConstraints);

        buttonCancel.setBackground(new java.awt.Color(204, 213, 174));
        buttonCancel.setFont(konfigurasi.getRobotoBold(14));
        buttonCancel.setText("Cancel");
        buttonCancel.setMaximumSize(new java.awt.Dimension(150, 50));
        buttonCancel.setMinimumSize(new java.awt.Dimension(150, 50));
        buttonCancel.setPreferredSize(new java.awt.Dimension(150, 50));
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelSU.add(buttonCancel, gridBagConstraints);

        buttonSignUp.setBackground(new java.awt.Color(204, 213, 174));
        buttonSignUp.setFont(konfigurasi.getRobotoBold(14));
        buttonSignUp.setText("Sign Up");
        buttonSignUp.setMaximumSize(new java.awt.Dimension(150, 50));
        buttonSignUp.setMinimumSize(new java.awt.Dimension(150, 50));
        buttonSignUp.setPreferredSize(new java.awt.Dimension(150, 50));
        buttonSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignUpActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        panelSU.add(buttonSignUp, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        panelSUBackground.add(panelSU, gridBagConstraints);

        panelSUSupport.setBackground(new java.awt.Color(204, 213, 174));
        panelSUSupport.setPreferredSize(new java.awt.Dimension(600, 450));
        panelSUSupport.setLayout(new java.awt.BorderLayout());

        labelSUTitle.setFont(konfigurasi.getPhilosopher(48));
        labelSUTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSUTitle.setText("YukDaftarYuk");
        labelSUTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelSUSupport.add(labelSUTitle, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panelSUBackground.add(panelSUSupport, gridBagConstraints);

        getContentPane().add(panelSUBackground, "SignUp");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSignInActionPerformed
        SignInAction();
    }//GEN-LAST:event_buttonSignInActionPerformed

    private void buttonCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateAccountActionPerformed
        card.show(getContentPane(), "SignUp");
    }//GEN-LAST:event_buttonCreateAccountActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        card.show(getContentPane(), "SignIn");
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSignUpActionPerformed
        SignUpAction();
    }//GEN-LAST:event_buttonSignUpActionPerformed

    private void buttonSignAsGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSignAsGuestActionPerformed
        PilihanBuku PB = new PilihanBuku();
        PB.setLocation(getLocation());
        PB.setSize(getSize());
        PB.setVisible(true);

        dispose();
    }//GEN-LAST:event_buttonSignAsGuestActionPerformed

    private void fieldSIPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldSIPasswordKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            SignInAction();
        }
    }//GEN-LAST:event_fieldSIPasswordKeyPressed

    private void fieldSUConPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldSUConPasswordKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            SignUpAction();
        }
    }//GEN-LAST:event_fieldSUConPasswordKeyPressed

    private void fieldSUPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldSUPasswordFocusGained
        labelSUPassword.setText("Password:");
        labelSUPassword.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_fieldSUPasswordFocusGained

    private void fieldSUEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldSUEmailFocusGained
        labelSUEmail.setText("Email:");
        labelSUEmail.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_fieldSUEmailFocusGained

    private void fieldSIEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldSIEmailFocusGained
        labelSIEmail.setText("Email:");
        labelSIEmail.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_fieldSIEmailFocusGained

    private void fieldSIPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldSIPasswordFocusGained
        labelSIPassword.setText("Password:");
        labelSIPassword.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_fieldSIPasswordFocusGained

    private void toTheNextPage(Pembeli pembeli) {
        PilihanBuku PB = new PilihanBuku(pembeli);
        PB.setLocation(getLocation());
        PB.setSize(getSize());
        PB.setVisible(true);

        dispose();
    }

    private void SignInAction() {
        fieldSIEmail.setText(fieldSIEmail.getText().toLowerCase());

        String email = fieldSIEmail.getText().trim();
        String passW = String.valueOf(fieldSIPassword.getPassword());

        try {
            if (email.equals("")) {
                labelSIEmail.setText("Email tidak boleh kosong.");
                labelSIEmail.setForeground(java.awt.Color.red);
                fieldSIPassword.setText("");
            } else if (passW.equals("")) {
                labelSIPassword.setText("Password tidak boleh kosong.");
                labelSIPassword.setForeground(java.awt.Color.red);
                fieldSIPassword.setText("");
            } else if (validateIN(new Regist(email, passW))) {
                Regist pembeli = new Regist(email, passW);
                boolean cek = pembeli.cekNamaPembeli();
                toTheNextPage(pembeli);
            } else {
                labelSIEmail.setText("Email atau password tidak ditemukan.");
                labelSIEmail.setForeground(java.awt.Color.red);
                fieldSIPassword.setText("");
            }
        } catch (IOException ex) {
            Logger.getLogger(Sign.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void SignUpAction() {
        fieldSUEmail.setText(fieldSUEmail.getText().toLowerCase());

        String email = fieldSUEmail.getText().trim();
        String passW = String.valueOf(fieldSUPassword.getPassword());
        String passC = String.valueOf(fieldSUConPassword.getPassword());

        try {
            if (email.equals("")) {
                labelSUEmail.setText("Email tidak boleh kosong.");
                labelSUEmail.setForeground(java.awt.Color.red);
                fieldSUPassword.setText("");
                fieldSUConPassword.setText("");
            } else if (passW.equals("")) {
                labelSUPassword.setText("Password tidak boleh kosong.");
                labelSUPassword.setForeground(java.awt.Color.red);
                fieldSUPassword.setText("");
                fieldSUConPassword.setText("");
            } else {
                validateUP(new Regist(email, passW), passC);
            }
        } catch (IOException ex) {
            Logger.getLogger(Sign.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public boolean validateIN(Regist pembeli) throws IOException {
        boolean cek = pembeli.cekNamaPembeli();
        return cek == true;
    }

    public void validateUP(Regist pembeli, String passC) throws IOException {
        if (pembeli.getPassword().equalsIgnoreCase(passC)) {
            if (pembeli.cekEmailPembeli()) {
                labelSUEmail.setText("Email sudah pernah digunakan.");
                labelSUEmail.setForeground(java.awt.Color.red);
                fieldSUPassword.setText("");
                fieldSUConPassword.setText("");
            } else {
                InfoPengguna dIP = new InfoPengguna(this, pembeli);
                dIP.setLocationRelativeTo(null);
                dIP.setVisible(true);
            }
        } else {
            labelSUPassword.setText("Password harus sesuai dengan konfirmasi.");
            labelSUPassword.setForeground(java.awt.Color.red);
            fieldSUPassword.setText("");
            fieldSUConPassword.setText("");
        }
    }

    private final CardLayout card;
    private Konfigurasi konfigurasi;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonCreateAccount;
    private javax.swing.JButton buttonSignAsGuest;
    private javax.swing.JButton buttonSignIn;
    private javax.swing.JButton buttonSignUp;
    private javax.swing.JTextField fieldSIEmail;
    private javax.swing.JPasswordField fieldSIPassword;
    private javax.swing.JPasswordField fieldSUConPassword;
    private javax.swing.JTextField fieldSUEmail;
    private javax.swing.JPasswordField fieldSUPassword;
    private javax.swing.JLabel labelSIEmail;
    private javax.swing.JLabel labelSIPassword;
    private javax.swing.JLabel labelSITitle;
    private javax.swing.JLabel labelSUConPassword;
    private javax.swing.JLabel labelSUEmail;
    private javax.swing.JLabel labelSUPassword;
    private javax.swing.JLabel labelSUTitle;
    private javax.swing.JPanel panelSI;
    private javax.swing.JPanel panelSIBackground;
    private javax.swing.JPanel panelSISupport;
    private javax.swing.JPanel panelSU;
    private javax.swing.JPanel panelSUBackground;
    private javax.swing.JPanel panelSUSupport;
    // End of variables declaration//GEN-END:variables
}
